<a href="https://colab.research.google.com/github/VivekReddy10-08-2004/USM_BAN_Big_Husky_Lovers/blob/main/Notebooks/BAN_Hackathon_basic_data_exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("https://raw.githubusercontent.com/VivekReddy10-08-2004/USM_BAN_Big_Husky_Lovers/refs/heads/main/Open%20Reqs%20Mar%202026_2026-04-01.csv")

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216 entries, 0 to 215
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   JOB_REQUISITION                   216 non-null    object
 1   WORKER_SUB_TYPE                   216 non-null    object
 2   DAYS_OPEN                         216 non-null    object
 3   PRIMARY_LOCATION                  216 non-null    object
 4   JOB_PROFILE                       216 non-null    object
 5   MANAGEMENT_LEVEL_JOB_REQUISITION  211 non-null    object
 6   NUMBER_OF_OPENINGS_AVAILABLE      216 non-null    int64
 7   JOB_DESCRIPTION                   216 non-null    object
 8   JOB_PROFILE_SUMMARY               216 non-null    object
dtypes: int64(1), object(8)
memory usage: 15.3+ KB

In [10]:
df.shape

(216, 9)

In [11]:
df.head()

,JOB_REQUISITION,WORKER_SUB_TYPE,DAYS_OPEN,PRIMARY_LOCATION,JOB_PROFILE,MANAGEMENT_LEVEL_JOB_REQUISITION,NUMBER_OF_OPENINGS_AVAILABLE,JOB_DESCRIPTION,JOB_PROFILE_SUMMARY
0,"Director, Security Operations & Resilience (Open)",Regular,236 days ago,US,Director IT,Business Leader,1,PRIMARY DUTIES AND RESPONSIBILITIES: Directs b...,Directs business/function(s) activities in sup...
1,Employment Counsel (Open),Regular,85 days ago,US,Corporate Counsel,Expert Contributor,1,PRIMARY DUTIES AND RESPONSIBILITIES: Performs ...,Performs wide range of legal activities to sup...
2,R&D PCR Assay Development Scientist (Evergreen...,Regular,39 days ago,US,Scientist II,Expert Contributor,0,PRIMARY DUTIES AND RESPONSIBILITIES: Prepares ...,Performs a variety of scientific activities to...
3,Transportation Network Planner (Open),Regular,20 days ago,GB,Labs Transportation Associate Sr III,Advanced Contributor,1,PRIMARY DUTIES AND RESPONSIBILITIES: May be re...,"Performs a variety of physical, clerical and c..."
4,Field Sales Veterinary Diagnostics Santa Cruz ...,Regular,141 days ago,US,Veterinary Diagnostic Consultant II,Expert Contributor,1,PRIMARY DUTIES AND RESPONSIBILITIES: Increase ...,Create relationships with customers through kn...

In [17]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1-L6-lsX1c8sOaFIR6cG5JBFWfudLE3THPG8Iv5G9IPY/edit#gid=0

In [16]:
df.isna()

,JOB_REQUISITION,WORKER_SUB_TYPE,DAYS_OPEN,PRIMARY_LOCATION,JOB_PROFILE,MANAGEMENT_LEVEL_JOB_REQUISITION,NUMBER_OF_OPENINGS_AVAILABLE,JOB_DESCRIPTION,JOB_PROFILE_SUMMARY
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
211,False,False,False,False,False,False,False,False,False
212,False,False,False,False,False,False,False,False,False
213,False,False,False,False,False,False,False,False,False
214,False,False,False,False,False,False,False,False,False
215,False,False,False,False,False,False,False,False,False